{
 "title": "Active Series / Chunks",
 "panels": [
  {
   "title": "Series",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loki_ingester_memory_chunks{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"})",
     "legendFormat": "series"
    }
   ]
  },
  {
   "title": "Chunks per series",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loki_ingester_memory_chunks{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}) / sum(loki_ingester_memory_streams{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"})",
     "legendFormat": "chunks"
    }
   ]
  }
 ]
}
{
 "title": "Flush Stats",
 "panels": [
  {
   "title": "Utilization",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_utilization_bucket{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_ingester_chunk_utilization_bucket{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_ingester_chunk_utilization_sum{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval])) * 1 / sum(rate(loki_ingester_chunk_utilization_count{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Age",
   "type": "graph",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_age_seconds_bucket{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_ingester_chunk_age_seconds_bucket{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_ingester_chunk_age_seconds_sum{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval])) * 1e3 / sum(rate(loki_ingester_chunk_age_seconds_count{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}
{
 "title": "Flush Stats",
 "panels": [
  {
   "title": "Log Entries Per Chunk",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_entries_bucket{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_ingester_chunk_entries_bucket{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_ingester_chunk_entries_sum{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval])) * 1 / sum(rate(loki_ingester_chunk_entries_count{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Index Entries Per Chunk",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_chunk_store_index_entries_per_chunk_sum{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[5m])) / sum(rate(loki_chunk_store_index_entries_per_chunk_count{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[5m]))",
     "legendFormat": "Index Entries"
    }
   ]
  }
 ]
}
{
 "title": "Flush Stats",
 "panels": [
  {
   "title": "Queue Length",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cortex_ingester_flush_queue_length{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Flush Rate",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_ingester_chunk_age_seconds_count{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}
{
 "title": "Flush Stats",
 "panels": [
  {
   "title": "Chunks Flushed/Second",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_chunks_flushed_total{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Chunk Flush Reason",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (rate(loki_ingester_chunks_flushed_total{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval])) / ignoring(reason) group_left sum(rate(loki_ingester_chunks_flushed_total{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval]))",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}
{
 "title": "Utilization",
 "panels": [
  {
   "title": "Chunk Utilization",
   "type": "heatmap",
   "targets": [
    {
     "expr": "sum by (le) (rate(loki_ingester_chunk_utilization_bucket{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}
{
 "title": "Utilization",
 "panels": [
  {
   "title": "Chunk Size Bytes",
   "type": "heatmap",
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_chunk_size_bytes_bucket{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}
{
 "title": "Utilization",
 "panels": [
  {
   "title": "Chunk Size Quantiles",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_size_bytes_bucket{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(loki_ingester_chunk_size_bytes_bucket{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_ingester_chunk_size_bytes_bucket{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}
{
 "title": "Duration",
 "panels": [
  {
   "title": "Chunk Duration hours (end-start)",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(loki_ingester_chunk_bounds_hours_bucket{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_bounds_hours_bucket{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum(rate(loki_ingester_chunk_bounds_hours_sum{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[5m])) / sum(rate(loki_ingester_chunk_bounds_hours_count{cluster=\"$cluster\", job=~\"$namespace/(loki|enterprise-logs)-write\"}[5m]))",
     "legendFormat": "avg"
    }
   ]
  }
 ]
}
{
 "title": "Headlines",
 "panels": [
  {
   "title": "Number of Pending Requests",
   "type": "singlestat",
   "format": "none",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loki_compactor_pending_delete_requests_count{cluster=~\"$cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Oldest Pending Request Age",
   "type": "singlestat",
   "format": "dtdurations",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(loki_compactor_oldest_pending_delete_request_age_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\"})"
    }
   ]
  }
 ]
}
{
 "title": "Churn",
 "panels": [
  {
   "title": "Delete Requests Received / Day",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(loki_compactor_delete_requests_received_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[1d]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Delete Requests Processed / Day",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(loki_compactor_delete_requests_processed_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[1d]))",
     "legendFormat": "processed"
    }
   ]
  }
 ]
}
{
 "title": "Failures",
 "panels": [
  {
   "title": "Failures in Loading Delete Requests / Hour",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(loki_compactor_load_pending_requests_attempts_total{status=\"fail\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[1h]))",
     "legendFormat": "failures"
    }
   ]
  }
 ]
}
{
 "title": "Deleted lines",
 "panels": [
  {
   "title": "Lines Deleted / Sec",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_compactor_deleted_lines{cluster=~\"$cluster\",job=~\"$namespace/(loki|enterprise-logs)-read\"}[$__rate_interval])) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  }
 ]
}
{
 "title": "Loki / Logs",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(loki_build_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(loki_build_info{cluster=~\"$cluster\"}, namespace)"
   },
   { "name": "logs", "query": "loki" },
   {
    "name": "deployment",
    "query": "label_values(kube_deployment_created{cluster=\"$cluster\", namespace=\"$namespace\"}, deployment)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_container_info{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment.*\"}, pod)"
   },
   {
    "name": "container",
    "query": "label_values(kube_pod_container_info{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", pod=~\"$deployment.*\"}, container)"
   },
   { "name": "level", "query": "debug,info,warn,error" },
   { "name": "filter", "label": "LogQL Filter" }
  ]
 },
 "panels": [
  {
   "title": "goroutines",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment.*\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "gc duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment.*\", pod=~\"$pod\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment.*\", pod=~\"$pod\", container=~\"$container\"}[5m]))"
    }
   ]
  },
  {
   "title": "working set",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment.*\", pod=~\"$pod\", container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "tx",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment.*\", pod=~\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "rx",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment.*\", pod=~\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "restarts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment.*\", pod=~\"$pod\", container=~\"$container\"}[30m]) > 0",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "bad words",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_custom_bad_words_total{cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\", exported_pod=~\"$pod\", container=~\"$container\"}[5m])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Log Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment.*\", pod=~\"$pod\", container=~\"$container\" } |logfmt| level=\"$level\" |= \"$filter\" [5m])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment.*\", pod=~\"$pod\", container=~\"$container\"} | logfmt | level=\"$level\" |= \"$filter\""
    }
   ]
  }
 ]
}
{
 "title": "Recording Rules",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(loki_ruler_wal_samples_appended_total, tenant)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Appenders Not Ready",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(loki_ruler_wal_appender_ready) by (pod, tenant) == 0"
    }
   ]
  },
  {
   "title": "Samples Appended to WAL per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(loki_ruler_wal_samples_appended_total{tenant=~\"${tenant}\"}[$__rate_interval])) by (tenant) > 0",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Series Created per Second",
   "type": "timeseries",
   "description": "Series are unique combinations of labels",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(loki_ruler_wal_storage_created_series_total{tenant=~\"${tenant}\"}[$__rate_interval])) by (tenant) > 0",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Write Behind",
   "type": "timeseries",
   "description": "Difference between highest timestamp appended to WAL and highest timestamp successfully written to remote storage",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "loki_ruler_wal_prometheus_remote_storage_highest_timestamp_in_seconds{tenant=~\"${tenant}\"}\n- on (tenant)\n  (\n    loki_ruler_wal_prometheus_remote_storage_queue_highest_sent_timestamp_seconds{tenant=~\"${tenant}\"}\n    or vector(0)\n  )",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Samples Sent per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(loki_ruler_wal_prometheus_remote_storage_samples_total{tenant=~\"${tenant}\"}[$__rate_interval])) by (tenant) > 0",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "WAL Disk Size",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (tenant) (loki_ruler_wal_disk_size{tenant=~\"${tenant}\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Pending Samples",
   "type": "timeseries",
   "description": "Some number of pending samples is expected, but if remote-write is failing this value will remain high",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "max(loki_ruler_wal_prometheus_remote_storage_samples_pending{tenant=~\"${tenant}\"}) by (tenant,pod) > 0",
     "legendFormat": "{{tenant}}"
    }
   ]
  }
 ]
}
{
 "title": "Loki / Operational",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "logs", "query": "loki" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(loki_build_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(loki_build_info{cluster=~\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries/Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\nlabel_replace(\n  label_replace(\n        rate(loki_request_duration_seconds_count{cluster=\"$cluster\", job=~\"($namespace)/cortex-gw\", route=~\"api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}[5m]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n\"status\", \"${1}\", \"status_code\", \"([a-z]+)\")\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Pushes/Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\nlabel_replace(\n  label_replace(\n          rate(loki_request_duration_seconds_count{cluster=\"$cluster\", job=~\"($namespace)/cortex-gw\", route=~\"api_prom_push|loki_api_v1_push\"}[5m]),\n   \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n\"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Bad Words",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (name,level) (rate(promtail_custom_bad_words_total{cluster=\"$cluster\", exported_namespace=\"$namespace\"}[$__interval])) - \nsum by (name,level) (rate(promtail_custom_bad_words_total{cluster=\"$cluster\", exported_namespace=\"$namespace\"}[$__interval] offset 1h)))",
     "legendFormat": "{{name}}-{{level}}"
    }
   ]
  },
  {
   "title": "Lines Per Tenant (top 10)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(loki_distributor_lines_received_total{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "MBs Per Tenant (Top 10)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(loki_distributor_bytes_received_total{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (tenant)) / 1024 / 1024",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\"}[10m]) > 0",
     "legendFormat": "{{container}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Push Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/cortex-gw\", route=~\"api_prom_push|loki_api_v1_push\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/cortex-gw\", route=~\"api_prom_push|loki_api_v1_push\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/cortex-gw\", route=~\"api_prom_push|loki_api_v1_push\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Distributor Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (job:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/write\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (job:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/write\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (job:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/write\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Distributor Success Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/write\", status_code!~\"5[0-9]{2}\"}[5m])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/write\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Ingester Latency Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/write\", route=\"/logproto.Pusher/Push\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/write\", route=\"/logproto.Pusher/Push\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/write\", route=\"/logproto.Pusher/Push\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Ingester Success Rate Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/write\", status_code!~\"5[0-9]{2}\", route=\"/logproto.Pusher/Push\"}[5m])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/write\", route=\"/logproto.Pusher/Push\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(loki|enterprise-logs)-read\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", cluster=\"$cluster\"}))",
     "legendFormat": "{{route}}-.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(loki|enterprise-logs)-read\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", cluster=\"$cluster\"}))",
     "legendFormat": "{{route}}-.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(loki|enterprise-logs)-read\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", cluster=\"$cluster\"}))",
     "legendFormat": "{{route}}-.5"
    }
   ]
  },
  {
   "title": "Querier Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(loki|enterprise-logs)-read\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", cluster=\"$cluster\"})) * 1e3",
     "legendFormat": ".99-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(loki|enterprise-logs)-read\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", cluster=\"$cluster\"})) * 1e3",
     "legendFormat": ".9-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(loki|enterprise-logs)-read\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", cluster=\"$cluster\"})) * 1e3",
     "legendFormat": ".5-{{route}}"
    }
   ]
  },
  {
   "title": "Querier Success Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/(loki|enterprise-logs)-read\", status_code!~\"5[0-9]{2}\"}[5m])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/(loki|enterprise-logs)-read\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Ingester Latency Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/write\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\", cluster=\"$cluster\"})) * 1e3",
     "legendFormat": ".99-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/write\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\", cluster=\"$cluster\"})) * 1e3",
     "legendFormat": ".9-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/write\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\", cluster=\"$cluster\"})) * 1e3",
     "legendFormat": ".5-{{route}}"
    }
   ]
  },
  {
   "title": "Ingester Success Rate Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/write\", status_code!~\"5[0-9]{2}\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\"}[5m])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/write\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Discarded Lines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,sum by (tenant, reason) (rate(loki_discarded_samples_total{cluster=\"$cluster\",namespace=\"$namespace\"}[1m])))",
       "legendFormat": "{{ tenant }} - {{ reason }}"
      }
     ]
    },
    {
     "title": "Discarded Lines Per Interval",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "topk(10, sum by (tenant, reason) (sum_over_time(increase(loki_discarded_samples_total{cluster=\"$cluster\",namespace=\"$namespace\"}[1m])[$__range:1m])))",
       "legendFormat": "{{ tenant }} - {{ reason }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Path",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"(loki|enterprise-logs)-write.*\"}",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"(loki|enterprise-logs)-write.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Error Log Rate",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate({cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/write\"} | logfmt | level=\"error\"[1m]))"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/write\"} | logfmt | level=\"error\""
      }
     ]
    },
    {
     "title": "Success Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/write\", status_code!~\"5[0-9]{2}\"}[5m])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/write\"}[5m])) by (route)",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Append Failures By Ingester",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_ingester_append_failures_total{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (ingester)",
       "legendFormat": "{{ingester}}"
      }
     ]
    },
    {
     "title": "Bytes Received/Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_bytes_received_total{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Lines Received/Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_lines_received_total{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Streams",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,sum by (tenant) (loki_ingester_memory_streams{cluster=\"$cluster\",job=~\"($namespace)/write\"}))",
       "legendFormat": "{{ tenant }}"
      }
     ]
    },
    {
     "title": "Streams Created/Sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum by (tenant) (rate(loki_ingester_streams_created_total{cluster=\"$cluster\",job=~\"($namespace)/write\"}[1m]) > 0))",
       "legendFormat": "{{ tenant }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chunks Flushed/Sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_chunks_flushed_total{cluster=\"$cluster\",job=~\"($namespace)/write\"}[1m]))",
       "legendFormat": "Chunks"
      },
      {
       "expr": "sum(increase(loki_chunk_store_deduped_chunks_total{cluster=\"$cluster\", job=~\"($namespace)/write\"}[1m]))/sum(increase(loki_ingester_chunks_flushed_total{cluster=\"$cluster\", job=~\"($namespace)/write\"}[1m])) < 1",
       "legendFormat": "De-Dupe Ratio"
      }
     ]
    },
    {
     "title": "Chunk Size Bytes",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_chunk_size_bytes_bucket{cluster=\"$cluster\",job=~\"($namespace)/write\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Chunk Flush Reason %",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by(reason) (rate(loki_ingester_chunks_flushed_total{cluster=~\"$cluster\",job=~\"$namespace/ingester\", namespace=~\"$namespace\"}[$__rate_interval])) / ignoring(reason) group_left sum(rate(loki_ingester_chunks_flushed_total{cluster=~\"$cluster\",job=~\"$namespace/ingester\", namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "Chunk Utilization",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "sum by (le) (rate(loki_ingester_chunk_utilization_bucket{cluster=\"$cluster\", job=~\"($namespace)/write\"}[1m]))",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Read Path",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"(loki|enterprise-logs)-read.*\"}",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"(loki|enterprise-logs)-read.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Error Log Rate",
     "type": "graph",
     "gridPos": { "h": 3, "w": 18, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate({cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/(loki|enterprise-logs)-read\"} | logfmt |  level=\"error\"[1m]))"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 18, "w": 18, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/(loki|enterprise-logs)-read\"} | logfmt | level=\"error\""
      }
     ]
    },
    {
     "title": "Success Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/(loki|enterprise-logs)-read\", status_code!~\"5[0-9]{2}\"}[1m])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/(loki|enterprise-logs)-read\"}[1m])) by (route)",
       "legendFormat": "{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memcached",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency By Method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(loki_memcache_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (method, name, le, container))",
       "legendFormat": "{{container}}: .99-{{method}}-{{name}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(loki_memcache_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (method, name, le, container))",
       "legendFormat": "{{container}}: .9-{{method}}-{{name}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(loki_memcache_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (method, name, le, container))",
       "legendFormat": "{{container}}: .5-{{method}}-{{name}}"
      }
     ]
    },
    {
     "title": "Status By Method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_memcache_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (status_code, method, name, container)",
       "legendFormat": "{{container}}: {{status_code}}-{{method}}-{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consul",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(loki_consul_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(loki_consul_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(loki_consul_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    },
    {
     "title": "Status By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_consul_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, status_code, method)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Big Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "MutateRows Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(loki_bigtable_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", operation=\"/google.bigtable.v2.Bigtable/MutateRows\"}[5m])) by (operation, le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(loki_bigtable_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", operation=\"/google.bigtable.v2.Bigtable/MutateRows\"}[5m])) by (operation, le))"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(loki_bigtable_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", operation=\"/google.bigtable.v2.Bigtable/MutateRows\"}[5m])) by (operation, le))"
      }
     ]
    },
    {
     "title": "ReadRows Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(loki_bigtable_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", operation=\"/google.bigtable.v2.Bigtable/ReadRows\"}[5m])) by (operation, le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(loki_bigtable_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", operation=\"/google.bigtable.v2.Bigtable/ReadRows\"}[5m])) by (operation, le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(loki_bigtable_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", operation=\"/google.bigtable.v2.Bigtable/ReadRows\"}[5m])) by (operation, le))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "GetTable Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(loki_bigtable_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", operation=\"/google.bigtable.admin.v2.BigtableTableAdmin/GetTable\"}[5m])) by (operation, le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(loki_bigtable_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", operation=\"/google.bigtable.admin.v2.BigtableTableAdmin/GetTable\"}[5m])) by (operation, le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(loki_bigtable_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", operation=\"/google.bigtable.admin.v2.BigtableTableAdmin/GetTable\"}[5m])) by (operation, le))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "ListTables Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(loki_bigtable_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", operation=\"/google.bigtable.admin.v2.BigtableTableAdmin/ListTables\"}[5m])) by (operation, le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(loki_bigtable_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", operation=\"/google.bigtable.admin.v2.BigtableTableAdmin/ListTables\"}[5m])) by (operation, le))"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(loki_bigtable_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", operation=\"/google.bigtable.admin.v2.BigtableTableAdmin/ListTables\"}[5m])) by (operation, le))"
      }
     ]
    },
    {
     "title": "MutateRows Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_bigtable_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", operation=\"/google.bigtable.v2.Bigtable/MutateRows\"}[5m])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "ReadRows Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_bigtable_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", operation=\"/google.bigtable.v2.Bigtable/ReadRows\"}[5m])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "GetTable Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_bigtable_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", operation=\"/google.bigtable.admin.v2.BigtableTableAdmin/GetTable\"}[5m])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "ListTables Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_bigtable_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", operation=\"/google.bigtable.admin.v2.BigtableTableAdmin/ListTables\"}[5m])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GCS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(loki_gcs_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(loki_gcs_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(loki_gcs_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    },
    {
     "title": "Status By Method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_gcs_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dynamo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failure Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_dynamo_failures_total{cluster=\"$cluster\", namespace=\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Consumed Capacity Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_dynamo_consumed_capacity_total{cluster=\"$cluster\", namespace=\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Throttled Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_dynamo_throttled_total{cluster=\"$cluster\", namespace=\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Dropped Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_dynamo_dropped_requests_total{cluster=\"$cluster\", namespace=\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Query Pages",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(cortex_dynamo_query_pages_count{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(cortex_dynamo_query_pages_count{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(cortex_dynamo_query_pages_count{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(cortex_dynamo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(cortex_dynamo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(cortex_dynamo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    },
    {
     "title": "Status By Method",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_dynamo_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "S3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(loki_s3_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(loki_s3_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(loki_s3_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    },
    {
     "title": "Status By Method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_s3_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Azure Blob",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(loki_azure_blob_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(loki_azure_blob_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(loki_azure_blob_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    },
    {
     "title": "Status By Method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_azure_blob_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BoltDB Shipper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    },
    {
     "title": "Status By Method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_boltdb_shipper_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Ingester",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"(loki|enterprise-logs)-write.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_cpu_quota{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"(loki|enterprise-logs)-write.*\"} / container_spec_cpu_period{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"(loki|enterprise-logs)-write.*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"(loki|enterprise-logs)-write.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"(loki|enterprise-logs)-write.*\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", job=~\"($namespace)/read\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}
{
 "title": "Read Path",
 "panels": [
  {
   "title": "QPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_request_duration_seconds_count{cluster=~\"$cluster\",job=~\"($namespace)/(loki|enterprise-logs)-read\", route=~\"loki_api_v1_series|api_prom_series|api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_labels|loki_api_v1_label_name_values\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(loki|enterprise-logs)-read\", route=~\"loki_api_v1_series|api_prom_series|api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_labels|loki_api_v1_label_name_values\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": "{{ route }} 99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(loki|enterprise-logs)-read\", route=~\"loki_api_v1_series|api_prom_series|api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_labels|loki_api_v1_label_name_values\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": "{{ route }} 50th Percentile"
    },
    {
     "expr": "1e3 * sum(job_route:loki_request_duration_seconds_sum:sum_rate{job=~\"($namespace)/(loki|enterprise-logs)-read\", route=~\"loki_api_v1_series|api_prom_series|api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_labels|loki_api_v1_label_name_values\", cluster=~\"$cluster\"}) by (route)  / sum(job_route:loki_request_duration_seconds_count:sum_rate{job=~\"($namespace)/(loki|enterprise-logs)-read\", route=~\"loki_api_v1_series|api_prom_series|api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_labels|loki_api_v1_label_name_values\", cluster=~\"$cluster\"}) by (route) ",
     "legendFormat": "{{ route }} Average"
    }
   ]
  }
 ]
}
{
 "title": "BoltDB Shipper",
 "panels": [
  {
   "title": "QPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_boltdb_shipper_request_duration_seconds_count{cluster=~\"$cluster\",job=~\"($namespace)/(loki|enterprise-logs)-read\", operation=\"Shipper.Query\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{cluster=~\"$cluster\",job=~\"($namespace)/(loki|enterprise-logs)-read\", operation=\"Shipper.Query\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{cluster=~\"$cluster\",job=~\"($namespace)/(loki|enterprise-logs)-read\", operation=\"Shipper.Query\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_boltdb_shipper_request_duration_seconds_sum{cluster=~\"$cluster\",job=~\"($namespace)/(loki|enterprise-logs)-read\", operation=\"Shipper.Query\"}[$__rate_interval])) * 1e3 / sum(rate(loki_boltdb_shipper_request_duration_seconds_count{cluster=~\"$cluster\",job=~\"($namespace)/(loki|enterprise-logs)-read\", operation=\"Shipper.Query\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}
{
 "title": "Resource Usage",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"(loki|enterprise-logs)-read.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_cpu_quota{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"(loki|enterprise-logs)-read.*\"} / container_spec_cpu_period{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"(loki|enterprise-logs)-read.*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"(loki|enterprise-logs)-read.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"(loki|enterprise-logs)-read.*\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", job=~\"($namespace)/(loki|enterprise-logs)-read\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}
{
 "title": "Compact and Mark",
 "panels": [
  {
   "title": "Last Compact and Mark Operation Success",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loki_boltdb_shipper_compact_tables_operation_last_successful_run_timestamp_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\"} * 1e3"
    }
   ]
  },
  {
   "title": "Compact and Mark Operations Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "loki_boltdb_shipper_compact_tables_operation_duration_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Compact and Mark Operations Per Status",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status)(rate(loki_boltdb_shipper_compact_tables_operation_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{success}}"
    }
   ]
  }
 ]
}
{
 "title": "Per Table Marker",
 "panels": [
  {
   "title": "Processed Tables Per Action",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(action)(loki_boltdb_shipper_retention_marker_table_processed_total{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Modified Tables",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(table,action)(loki_boltdb_shipper_retention_marker_table_processed_total{cluster=~\"$cluster\", namespace=~\"$namespace\" , action=~\"modified|deleted\"})",
     "legendFormat": "{{table}}-{{action}}"
    }
   ]
  },
  {
   "title": "Marks Creation Rate Per Table",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table)(rate(loki_boltdb_shipper_retention_marker_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) >0",
     "legendFormat": "{{table}}"
    }
   ]
  }
 ]
}
{
 "panels": [
  {
   "title": "Marked Chunks (24h)",
   "type": "singlestat",
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(loki_boltdb_shipper_retention_marker_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[24h]))"
    }
   ]
  },
  {
   "title": "Mark Table Latency",
   "type": "graph",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_boltdb_shipper_retention_marker_table_processed_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_boltdb_shipper_retention_marker_table_processed_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_boltdb_shipper_retention_marker_table_processed_duration_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) * 1e3 / sum(rate(loki_boltdb_shipper_retention_marker_table_processed_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}
{
 "title": "Sweeper",
 "panels": [
  {
   "title": "Delete Chunks (24h)",
   "type": "singlestat",
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\"}[24h]))"
    }
   ]
  },
  {
   "title": "Delete Latency",
   "type": "graph",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) * 1e3 / sum(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}
{
 "panels": [
  {
   "title": "Sweeper Lag",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - (loki_boltdb_shipper_retention_sweeper_marker_file_processing_current_time{cluster=~\"$cluster\", namespace=~\"$namespace\"} > 0)",
     "legendFormat": "lag"
    }
   ]
  },
  {
   "title": "Marks Files to Process",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loki_boltdb_shipper_retention_sweeper_marker_files_current{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Delete Rate Per Status",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status)(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}
{
 "title": "Logs",
 "panels": [
  {
   "title": "Compactor Logs",
   "type": "logs",
   "targets": [
    {
     "expr": "{cluster=~\"$cluster\", job=~\"($namespace)/(loki|enterprise-logs)-read\"}"
    }
   ]
  }
 ]
}
{
 "title": "Write Path",
 "panels": [
  {
   "title": "QPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_request_duration_seconds_count{cluster=~\"$cluster\",job=~\"($namespace)/write\", route=~\"api_prom_push|loki_api_v1_push|/httpgrpc.HTTP/Handle\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (job:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/write\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (job:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/write\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "1e3 * sum(job:loki_request_duration_seconds_sum:sum_rate{job=~\"($namespace)/write\", cluster=~\"$cluster\"}) / sum(job:loki_request_duration_seconds_count:sum_rate{job=~\"($namespace)/write\", cluster=~\"$cluster\"})",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}
{
 "title": "BoltDB Shipper",
 "panels": [
  {
   "title": "QPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_boltdb_shipper_request_duration_seconds_count{cluster=~\"$cluster\",job=~\"($namespace)/write\", operation=\"WRITE\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{cluster=~\"$cluster\",job=~\"($namespace)/write\", operation=\"WRITE\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{cluster=~\"$cluster\",job=~\"($namespace)/write\", operation=\"WRITE\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_boltdb_shipper_request_duration_seconds_sum{cluster=~\"$cluster\",job=~\"($namespace)/write\", operation=\"WRITE\"}[$__rate_interval])) * 1e3 / sum(rate(loki_boltdb_shipper_request_duration_seconds_count{cluster=~\"$cluster\",job=~\"($namespace)/write\", operation=\"WRITE\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}