{
 "title": "Kubernetes / Compute Resources / Account",
 "tags": [ "loft-grafana-dashboard" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account",
    "query": "label_values(kube_namespace_labels{}, label_kiosk_sh_account)"
   }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (label_kiosk_sh_account)"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from requests)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (label_kiosk_sh_account) / sum(sum(kube_pod_container_resource_requests_cpu_cores) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (label_kiosk_sh_account)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (label_kiosk_sh_account) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Memory Utilization (from requests)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (label_kiosk_sh_account) / sum(sum(kube_pod_container_resource_requests_memory_bytes) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (label_kiosk_sh_account)"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(kube_pod_owner) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}"
    },
    {
     "expr": "sum(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (namespace) / sum(sum(kube_pod_container_resource_requests_cpu_cores) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}"
    },
    {
     "expr": "sum(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (namespace) / sum(sum(kube_pod_container_resource_limits_cpu_cores) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (namespace)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container!=\"\"}) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Memory Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Requests By Namespace",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(kube_pod_owner) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}"
    },
    {
     "expr": "sum(container_memory_rss{container!=\"\"}) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}"
    },
    {
     "expr": "sum(sum(container_memory_rss{container!=\"\"}) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (namespace) / sum(sum(kube_pod_container_resource_requests_memory_bytes) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}"
    },
    {
     "expr": "sum(sum(container_memory_rss{container!=\"\"}) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (namespace) / sum(sum(kube_pod_container_resource_limits_memory_bytes) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (namespace)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Current Network Usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\".+\"}[5m])) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\".+\"}[5m])) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=~\".+\"}[5m])) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{namespace=~\".+\"}[5m])) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\".+\"}[5m])) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=~\".+\"}[5m])) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\".+\"}[5m])) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\".+\"}[5m])) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Average Container Bandwidth by Namespace: Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{namespace=~\".+\"}[5m])) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Average Container Bandwidth by Namespace: Transmitted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{namespace=~\".+\"}[5m])) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Rate of Received Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=~\".+\"}[5m])) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Rate of Transmitted Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_total{namespace=~\".+\"}[5m])) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\".+\"}[5m])) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=~\".+\"}[5m])) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes / Cost / Account",
 "tags": [ "loft-grafana-dashboard" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "core_cost_per_hour", "query": "0.027" },
   { "name": "mem_gig_cost_per_hour", "query": "0.013" },
   {
    "name": "account",
    "query": "label_values(kube_namespace_labels{}, label_kiosk_sh_account)"
   }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Cost Per Hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (label_kiosk_sh_account) * $core_cost_per_hour + sum(sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (label_kiosk_sh_account) / 1024 / 1024 / 1024 * $mem_gig_cost_per_hour"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (label_kiosk_sh_account)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (label_kiosk_sh_account) / 1024 / 1024"
    }
   ]
  },
  { "title": "Costs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Cost Per Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (namespace) * $core_cost_per_hour + sum(sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (namespace) / 1024 / 1024 / 1024 * $mem_gig_cost_per_hour",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Cost Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Cost Per Namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (namespace) * $core_cost_per_hour + sum(sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (namespace) / 1024 / 1024 / 1024 * $mem_gig_cost_per_hour"
    },
    {
     "expr": "sum(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (namespace)"
    },
    {
     "expr": "sum(sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account=\"$account\"}) by (namespace) / 1024 / 1024"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes / Cost / Cluster",
 "tags": [ "loft-grafana-dashboard" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "core_cost_per_hour", "query": "0.027" },
   { "name": "mem_gig_cost_per_hour", "query": "0.013" }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Cost Per Hour $",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) * $core_cost_per_hour + sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) / 1024 / 1024 / 1024 * $mem_gig_cost_per_hour"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{container!=\"\"}) / 1024 / 1024"
    }
   ]
  },
  { "title": "Cost Per Account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Cost Per Hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels) by (label_kiosk_sh_account) * $core_cost_per_hour + sum(sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels) by (label_kiosk_sh_account) / 1024 / 1024 / 1024 * $mem_gig_cost_per_hour",
     "legendFormat": "{{label_kiosk_sh_account}}"
    }
   ]
  },
  { "title": "Cost Per Account Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total Cost",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_namespace_labels{label_kiosk_sh_account!=\"\"}) by (label_kiosk_sh_account)"
    },
    {
     "expr": "sum(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account!=\"\"}) by (label_kiosk_sh_account) * $core_cost_per_hour + sum(sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels) by (label_kiosk_sh_account) / 1024 / 1024 / 1024 * $mem_gig_cost_per_hour"
    },
    {
     "expr": "sum(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account!=\"\"}) by (label_kiosk_sh_account)"
    },
    {
     "expr": "sum(sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account!=\"\"}) by (label_kiosk_sh_account) / 1024 / 1024"
    }
   ]
  },
  { "title": "Cost Per Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Total Cost Per Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * $core_cost_per_hour + sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) / 1024 / 1024 / 1024 * $mem_gig_cost_per_hour",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Cost Per Namespace Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Total Cost",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_owner) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * $core_cost_per_hour + sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) / 1024 / 1024 / 1024 * $mem_gig_cost_per_hour"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) / 1024 / 1024"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes / Cost / Namespace",
 "tags": [ "loft-grafana-dashboard" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "core_cost_per_hour", "query": "0.027" },
   { "name": "mem_gig_cost_per_hour", "query": "0.013" },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info{}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Cost Per Hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) * $core_cost_per_hour + sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"}) / 1024 / 1024 / 1024 * $mem_gig_cost_per_hour"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\", container!=\"\"}) / 1024 / 1024"
    }
   ]
  },
  { "title": "Costs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Cost Per Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod) * $core_cost_per_hour + sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (pod) / 1024 / 1024 / 1024 * $mem_gig_cost_per_hour",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Cost Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Cost Per Pod",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod) * $core_cost_per_hour + sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (pod) / 1024 / 1024 / 1024 * $mem_gig_cost_per_hour"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (pod) / 1024 / 1024"
    }
   ]
  }
 ]
}